### ISSUE TITLE
Bug on project init

### ISSUE THREAD

**Issue by JulienTD** [ImOverlord/inject-cli#1]
I typed the command: inject init CLint and then I got this:

[***@*** ***]$ inject init CLint
npm WARN CLint@1.0.0 No description
npm WARN CLint@1.0.0 No repository field.
npm WARN CLint@1.0.0 No description
npm WARN CLint@1.0.0 No repository field.
/usr/lib/node_modules/inject-cli/dist/Creator/Creator.js:33
        fs.copyFileSync(__dirname + "/../../resource/tsconfig.json", "./tsconfig.json");
           ^

TypeError: fs.copyFileSync is not a function
    at Creator.createProjectDir (/usr/lib/node_modules/inject-cli/dist/Creator/Creator.js:33:12)
    at Creator.handler (/usr/lib/node_modules/inject-cli/dist/Creator/Creator.js:23:14)
    at Object.<anonymous> (/usr/lib/node_modules/inject-cli/dist/app.js:14:13)
    at Module._compile (module.js:577:32)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.runMain (module.js:611:10)
    at run (bootstrap_node.js:394:7)

**Comment by ImOverlord** [comment]
Thanks for spotting this bug.

This bug was fixed with v0.0.3 (5e8a2d83b221f56f2c2e98fc9a368cc20e734cb1).

I'll leave this issue open until we are sure the bug was fixed.
